package com.gonerp.taskmanager.model.enums;

/**
 * Origin of a POD_DESIGN card: whether the design idea was generated by a
 * designer or by a seller. Only meaningful for POD_DESIGN boards; null elsewhere.
 */
public enum CardGenType {
    DESIGNER, SELLER
}
