# Application
spring.application.name=gonErp
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gonerp
spring.datasource.username=steve
spring.datasource.password=dev12489$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT
app.jwt.secret=fztTWV+g4CYPH4tQXjZ5/vo7WPRFg2XTsLDVCXSa5XY=
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:9000,http://localhost:3000

# File Upload
app.upload.dir=uploads/images
app.upload.taskmanager=uploads/taskmanager
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.gonerp=DEBUG
