# Application
spring.application.name=gonErp
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gonerp
spring.datasource.username=steve
spring.datasource.password=dev12489$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT
app.jwt.secret=fztTWV+g4CYPH4tQXjZ5/vo7WPRFg2XTsLDVCXSa5XY=
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:9000,http://localhost:3000

# File Upload
app.upload.dir=uploads/images
app.upload.taskmanager=uploads/taskmanager
app.upload.users=uploads/users
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# R2 Storage
app.storage.r2.endpoint=https://e50c630f35aa8ff8293c2c818767447e.r2.cloudflarestorage.com
app.storage.r2.access-key=685f6950f76e4ac59ed5fbda99b97efe
app.storage.r2.secret-key=54f50f8afd760ae81454fbf08c3b9898962c0e91a27d4aa19fda6830bb3aa049
app.storage.r2.bucket=dev-gonerp
app.storage.r2.public-url=https://pub-6ad7ac5ae44c4acb93346d886682cc76.r2.dev

# Logging
logging.level.com.gonerp=DEBUG
